/* AUTO-GENERATED by export_models_to_c.py — DO NOT EDIT */
#ifndef SCALER_PARAMS_H
#define SCALER_PARAMS_H

#define NUM_FEATURES  8

/* Feature names (for reference):
   [0] mean
   [1] std
   [2] min
   [3] max
   [4] pct25
   [5] pct75
   [6] diff_mean
   [7] diff_std
*/

static const float FEATURE_MIN[NUM_FEATURES] = {
    0.12198100f,
    0.10921325f,
    0.00000000f,
    1.00000000f,
    0.02903632f,
    0.05510058f,
    -0.00546463f,
    0.03120134f,
};

static const float FEATURE_MAX[NUM_FEATURES] = {
    0.93286330f,
    0.34865230f,
    0.00000000f,
    1.00000000f,
    0.96838433f,
    0.98230082f,
    0.01010101f,
    0.25279695f,
};

/* Label map (classifier output index -> signal type name) */
#define NUM_CLASSES  6
static const char* LABEL_NAMES[NUM_CLASSES] = {
    "burst",
    "drift",
    "mixed",
    "noisy",
    "periodic",
    "smooth",
};

#endif /* SCALER_PARAMS_H */
