/*
 * ai_pipeline.c
 * ===========================================================================
 * AIoT-MOR-ALDC Inference Pipeline — Implementation
 *
 * DEPENDENCY: The following headers MUST exist in src/ai/models/
 *   - classifier_model.h   (generated by export_models_to_c.py)
 *   - anomaly_model.h      (generated by export_models_to_c.py)
 *   - compression_model.h  (generated by export_models_to_c.py)
 *   - scaler_params.h      (generated by export_models_to_c.py)
 *
 * HOW emlearn models work:
 *   Each .h file exposes one function:
 *     int <name>_predict(const float *features, int n_features);
 *   Returns the predicted class index (classifier) or +1/-1 (IsolationForest).
 * ===========================================================================
 */

#include "ai_pipeline.h"
#include "models/scaler_params.h"       /* FEATURE_MIN, FEATURE_MAX, LABEL_NAMES */
#include "models/classifier_model.h"    /* classifier_model_predict()             */
#include "models/anomaly_model.h"       /* anomaly_model_predict()                */
#include "models/compression_model.h"   /* compression_model_predict()            */

#include <math.h>
#include <string.h>

/* ── Sorting helper for percentile calculation ─────────────────────────── */
static int compare_float(const void *a, const void *b)
{
    float fa = *(const float *)a;
    float fb = *(const float *)b;
    return (fa > fb) - (fa < fb);
}

/*
 * percentile() — compute the p-th percentile of sorted array.
 * arr MUST be sorted in ascending order before calling.
 */
static float percentile(float *sorted, uint32_t n, float p)
{
    float idx = (p / 100.0f) * (float)(n - 1);
    uint32_t lo = (uint32_t)idx;
    uint32_t hi = lo + 1;
    if (hi >= n)  return sorted[n - 1];
    float frac = idx - (float)lo;
    return sorted[lo] + frac * (sorted[hi] - sorted[lo]);
}

/* ==========================================================================
 * extract_features()
 *
 * Computes the same 8 features as the Python function
 * extract_features_from_signal() in export_models_to_c.py.
 *
 * CRITICAL: Any change here MUST be mirrored in the Python script,
 *           otherwise inference results will be wrong.
 * ========================================================================== */
static void extract_features(const float *signal, uint32_t n, float *feat)
{
    /* ── mean ──────────────────────────────────────────────────────────── */
    double sum = 0.0;
    for (uint32_t i = 0; i < n; i++)  sum += signal[i];
    float mean = (float)(sum / (double)n);

    /* ── std ───────────────────────────────────────────────────────────── */
    double var = 0.0;
    for (uint32_t i = 0; i < n; i++)
    {
        double d = signal[i] - mean;
        var += d * d;
    }
    float std_val = sqrtf((float)(var / (double)n));

    /* ── min, max ──────────────────────────────────────────────────────── */
    float vmin = signal[0], vmax = signal[0];
    for (uint32_t i = 1; i < n; i++)
    {
        if (signal[i] < vmin)  vmin = signal[i];
        if (signal[i] > vmax)  vmax = signal[i];
    }

    /* ── percentiles (need a sorted copy) ─────────────────────────────── */
    static float sorted_buf[AI_WINDOW_SIZE];   /* static avoids stack pressure */
    memcpy(sorted_buf, signal, n * sizeof(float));
    /* Simple insertion sort for 100 elements — fast enough at this size */
    for (uint32_t i = 1; i < n; i++)
    {
        float key = sorted_buf[i];
        int32_t j = (int32_t)i - 1;
        while (j >= 0 && sorted_buf[j] > key)
        {
            sorted_buf[j + 1] = sorted_buf[j];
            j--;
        }
        sorted_buf[j + 1] = key;
    }
    float pct25 = percentile(sorted_buf, n, 25.0f);
    float pct75 = percentile(sorted_buf, n, 75.0f);

    /* ── diff mean & diff std ──────────────────────────────────────────── */
    static float diff_buf[AI_WINDOW_SIZE - 1];
    double diff_sum = 0.0;
    for (uint32_t i = 0; i < n - 1; i++)
    {
        diff_buf[i] = signal[i + 1] - signal[i];
        diff_sum   += diff_buf[i];
    }
    float diff_mean = (float)(diff_sum / (double)(n - 1));

    double diff_var = 0.0;
    for (uint32_t i = 0; i < n - 1; i++)
    {
        double d = diff_buf[i] - diff_mean;
        diff_var += d * d;
    }
    float diff_std = sqrtf((float)(diff_var / (double)(n - 1)));

    /* ── Pack into output array ────────────────────────────────────────── */
    feat[0] = mean;
    feat[1] = std_val;
    feat[2] = vmin;
    feat[3] = vmax;
    feat[4] = pct25;
    feat[5] = pct75;
    feat[6] = diff_mean;
    feat[7] = diff_std;
}

/* ==========================================================================
 * normalise_signal() — per-window [0,1] normalisation
 * Matches Python: normalize_signal() in export_models_to_c.py
 * ========================================================================== */
static void normalise_signal(const float *in, float *out, uint32_t n)
{
    float vmin = in[0], vmax = in[0];
    for (uint32_t i = 1; i < n; i++)
    {
        if (in[i] < vmin) vmin = in[i];
        if (in[i] > vmax) vmax = in[i];
    }
    float range = vmax - vmin;
    if (range < 1e-9f)
    {
        memset(out, 0, n * sizeof(float));
        return;
    }
    for (uint32_t i = 0; i < n; i++)
        out[i] = (in[i] - vmin) / range;
}

/* ==========================================================================
 * scale_features() — MinMax scaling of extracted features
 * Uses FEATURE_MIN / FEATURE_MAX from scaler_params.h
 * ========================================================================== */
static void scale_features(float *feat)
{
    for (uint32_t i = 0; i < AI_NUM_FEATURES; i++)
    {
        float range = FEATURE_MAX[i] - FEATURE_MIN[i];
        if (range < 1e-9f)
        {
            feat[i] = 0.0f;
        }
        else
        {
            feat[i] = (feat[i] - FEATURE_MIN[i]) / range;
            /* Clamp to [0, 1] for safety */
            if (feat[i] < 0.0f) feat[i] = 0.0f;
            if (feat[i] > 1.0f) feat[i] = 1.0f;
        }
    }
}

/* ==========================================================================
 * ai_pipeline_init
 * ========================================================================== */
void ai_pipeline_init(void)
{
    /* Nothing to initialise at runtime — models are compiled into Flash.
     * This function is a placeholder for future self-test code. */
}

/* ==========================================================================
 * ai_pipeline_run
 * ========================================================================== */
void ai_pipeline_run(const float *window_data, ai_result_t *result)
{
    static float norm_buf[AI_WINDOW_SIZE];    /* normalised signal */
    float feat[AI_NUM_FEATURES];

    /* Step 1: Normalise signal window to [0, 1] */
    normalise_signal(window_data, norm_buf, AI_WINDOW_SIZE);

    /* Step 2: Extract 8 statistical features */
    extract_features(norm_buf, AI_WINDOW_SIZE, feat);

    /* Step 3: Scale features using training-set min/max */
    memcpy(result->features, feat, sizeof(feat));
    scale_features(result->features);

    /* Step 4: Signal classification (Random Forest) */
    result->signal_class = classifier_model_predict(result->features, AI_NUM_FEATURES);
    if (result->signal_class >= 0 && result->signal_class < NUM_CLASSES)
        result->signal_class_name = LABEL_NAMES[result->signal_class];
    else
        result->signal_class_name = "unknown";

    /* Step 5: Anomaly detection (Decision Tree surrogate model)
     *   anomaly_model_predict returns: 1 = anomaly, 0 = normal */
    int iso_out = anomaly_model_predict(result->features, AI_NUM_FEATURES);
    result->is_anomaly = (iso_out == 1);

    /* Step 6: Compression-mode decision (Decision Tree)
     *   Returns: 1 = compress, 0 = skip */
    int cm_out = compression_model_predict(result->features, AI_NUM_FEATURES);
    result->do_compress = (cm_out == 1) && (!result->is_anomaly);
    /* Safety rule: never compress anomalous data — transmit it raw */
}
